services:
    posts-comments:
        container_name: ${POSTS_SERVICE_HOSTNAME}
        hostname: ${POSTS_SERVICE_HOSTNAME}
        image: ${POSTS_SERVICE_HOSTNAME}
        env_file:
            -   path: "../.env"
                required: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "${POSTS_SERVICE_PORT}:${POSTS_SERVICE_PORT}"
        volumes:
            - "./:/home/posts-comments"
        networks:
            - social365-network
        depends_on:
            posts-cassandra:
                condition: service_healthy
            profile-service:
                condition: service_healthy
            images-service:
                condition: service_healthy
            config-server:
                condition: service_healthy
            eureka-registry:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${POSTS_SERVICE_PORT}/actuator/health" ]
            start_period: 15s
            interval: 10s
            timeout: 10s
            retries: 10

    posts-cassandra:
        container_name: ${POSTS_CASSANDRA_HOSTNAME}
        hostname: ${POSTS_CASSANDRA_HOSTNAME}
        image: ${POSTS_CASSANDRA_HOSTNAME}
        env_file:
            -   path: "../.env"
                required: true
        build:
            context: cassandra
            dockerfile: Dockerfile
        ports:
            - "${POSTS_CASSANDRA_PORT}:${POSTS_CASSANDRA_PORT}"
        environment:
            - CASSANDRA_CLUSTER_NAME=${POSTS_CASSANDRA_CLUSTER_NAME}
        command: "sh /cassandra_init.sh"
        networks:
            - social365-network
        healthcheck:
            test: cqlsh -u cassandra -p ${POSTS_CASSANDRA_PASSWORD} -k ${POSTS_CASSANDRA_KEYSPACE_NAME}
            start_period: 15s
            interval: 10s
            timeout: 10s
            retries: 10
