services:
    notifications-gateway:
        container_name: ${NOTIFICATIONS_GATEWAY_HOSTNAME}
        image: ${NOTIFICATIONS_GATEWAY_HOSTNAME}:prod
        hostname: ${NOTIFICATIONS_GATEWAY_HOSTNAME}
        build:
            context: .
            dockerfile: Dockerfile
        env_file: "../.env"
        networks:
            - social365-network
        ports:
            - "${NOTIFICATIONS_GATEWAY_PORT}:${NOTIFICATIONS_GATEWAY_PORT}"
        depends_on:
            config-server:
                condition: service_healthy
            eureka-registry:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${NOTIFICATIONS_GATEWAY_PORT}/actuator/health" ]
            start_period: 35s
            interval: 10s
            timeout: 5s
            retries: 3
