export enum ProfileMappings {
    PROFILE_API_MAPPING = "/api/v1/profile",

    GET_PROFILE_SUMMARY_MAPPING = PROFILE_API_MAPPING + "/summary",

    GET_POST_PROFILE_INFO_MAPPING = PROFILE_API_MAPPING + "/postInfo",

    CREATE_USERS_PROFILE_MAPPING = PROFILE_API_MAPPING + "/create",

    GET_BASIC_PROFILE_INFO_MAPPING = PROFILE_API_MAPPING + "/basicInfo",

    UPDATE_PROFILE_BIO_MAPPING = PROFILE_API_MAPPING + "/updateBio",

    GET_TODAY_BIRTHDAYS_MAPPING = PROFILE_API_MAPPING + "/todayBirthdays",
}
