export enum ProfileMappings {
    PROFILE_API_MAPPING = "/api/v1/profile",

    GET_PROFILE_SUMMARY_MAPPING = PROFILE_API_MAPPING + "/summary",

    GET_POST_PROFILE_INFO_MAPPING = PROFILE_API_MAPPING + "/postInfo",

    GET_BASIC_PROFILE_INFO_BY_USERNAME_MAPPING = PROFILE_API_MAPPING + "/basicInfoByUsername",

    GET_BASIC_PROFILE_INFO_MAPPING = PROFILE_API_MAPPING + "/basicInfo",

    UPDATE_PROFILE_BIO_MAPPING = PROFILE_API_MAPPING + "/updateBio",

    GET_TODAY_BIRTHDAYS_MAPPING = PROFILE_API_MAPPING + "/todayBirthdays",

    GET_PROFILES_BY_PATTERN_MAPPING = PROFILE_API_MAPPING + "/profilesByPattern"
}
