export enum DetailsType {
    HIGH_SCHOOL = "HIGH_SCHOOL",
    WORKPLACE = "WORKPLACE",
    CURRENT_CITY = "CURRENT_CITY",
    HOMETOWN = "HOMETOWN",
    RELATIONSHIP_STATUS = "RELATIONSHIP_STATUS",
    MAIL = "MAIL",
    PHONE = "PHONE",
    BIRTHDAY = "BIRTHDAY",
    GENDER = "GENDER",
    COLLEGE = "COLLEGE",
}
