spring:
    application:
        name: ${IMAGES_SERVICE_HOSTNAME:images-service}

    config:
         import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME:config-server}:${CONFIG_SERVER_PORT:8888}

    cloud:
        refresh:
            enabled: false
