server:
    port: 8079

spring:
    application:
        name: data-init

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}
                    jwk-set-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}/oauth2/jwks
                    jws-algorithms: ${JWS_ALGORITHM}
