services:
    eureka-registry:
        container_name: ${EUREKA_REGISTRY_HOSTNAME}
        image: ${EUREKA_REGISTRY_HOSTNAME}
        hostname: ${EUREKA_REGISTRY_HOSTNAME}
        depends_on:
            config-server:
                condition: service_started
        build:
            context: .
            dockerfile: Dockerfile
        env_file: "../.env"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://${EUREKA_REGISTRY_HOSTNAME}:${EUREKA_REGISTRY_PORT}/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
        ports:
            - "${EUREKA_REGISTRY_PORT}:${EUREKA_REGISTRY_PORT}"
        networks:
            - social365-network
