services:
    eureka-registry:
        container_name: ${EUREKA_REGISTRY_HOSTNAME}
        image: ${EUREKA_REGISTRY_HOSTNAME}
        hostname: ${EUREKA_REGISTRY_HOSTNAME}
        depends_on:
            config-server:
                condition: service_started
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
            - path: "../.env"
              required: true
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://${EUREKA_REGISTRY_HOSTNAME}:${EUREKA_REGISTRY_PORT}/actuator/health" ]
            start_period: 25s
            interval: 10s
            timeout: 10s
            retries: 10
        volumes:
            -   "./:/home/eureka-registry"
        ports:
            - "${EUREKA_REGISTRY_PORT}:${EUREKA_REGISTRY_PORT}"
        networks:
            - social365-network
