FROM alpine:3.19.1 AS build

RUN apk update --no-cache && apk add --no-cache gradle

WORKDIR /eureka-server

COPY build.gradle .

COPY settings.gradle .

COPY src/ src/

RUN gradle build -x test

RUN mv build/libs/eureka-server-0.0.1-SNAPSHOT.jar eureka-server.jar

FROM alpine:3.19.1

WORKDIR /eureka-server

RUN apk update --no-cache && apk add --no-cache openjdk17-jre

COPY --from=build /eureka-server/eureka-server.jar .

EXPOSE 8080

CMD ["java", "-jar", "eureka-server.jar"]
