version: "3.8"

services:
    social365-keycloak-initializer:
        container_name: social365-keycloak-initializer
        env_file:
            -   .env
        image: social365-keycloak-initializer
        build:
            context: keycloak-initializer
            dockerfile: Dockerfile.dev
        depends_on:
            social365-keycloak:
                condition: service_healthy
        environment:
            - KCCFG_OVERRIDE_EXISTING=true
        volumes:
            - "./keycloak-initializer:/keycloak-initializer"
            - "./.cache/keycloak-initializer/.gradle:/keycloak-initializer/.gradle"
            - "./.cache/keycloak-initializer/build:/keycloak-initializer/build"

    social365-keycloak:
        container_name: social365-keycloak
        image: quay.io/keycloak/keycloak:20.0.1
        depends_on:
            social365-keycloak-postgres:
                condition: service_healthy
        env_file:
            - .env
        command: start-dev
        ports:
            - '8081:8080'
        healthcheck:
            test: "curl -f http://localhost:8080/admin || exit 1"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s

    social365-keycloak-postgres:
        container_name: social365-keycloak-postgres
        image: postgres:alpine
        env_file:
            - .env
        ports:
            - "5001:5432"
        healthcheck:
            test: "pg_isready -U keycloak"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s
