version: "3.8"

services:
    social365-keycloak-initializer:
        container_name: social365-keycloak-initializer
        image: social365-keycloak-initializer
        build:
            context: keycloak-initializer
            dockerfile: Dockerfile.prod
        depends_on:
            social365-keycloak:
                condition: service_healthy
        environment:
            - KCCFG_OVERRIDE_EXISTING=false
            - KC_SERVER_URL=http://social365-keycloak:8080

    social365-keycloak:
        container_name: social365-keycloak
        image: quay.io/keycloak/keycloak:20.0.1
        depends_on:
            social365-keycloak-postgres:
                condition: service_healthy
        environment:
            - KC_DB=postgres
            - KC_DB_URL=jdbc:postgresql://social365-keycloak-postgres:5432/keycloak
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB_USERNAME=keycloak
            - KC_DB_PASSWORD=none
        command: start-dev
        ports:
            - "8081:8080"
        healthcheck:
            test: "curl -f http://localhost:8080/admin || exit 1"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s

    social365-keycloak-postgres:
        container_name: social365-keycloak-postgres
        image: postgres:alpine
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=none
        ports:
            - "5001:5432"
        healthcheck:
            test: "pg_isready -U keycloak"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s