services:
    api-gateway:
        container_name: ${API_GATEWAY_HOSTNAME}
        image: ${API_GATEWAY_HOSTNAME}:prod
        hostname: ${API_GATEWAY_HOSTNAME}
        depends_on:
            eureka-registry:
                condition: service_healthy
            config-server:
                condition: service_healthy
            posts-comments:
                condition: service_healthy
            profile-service:
                condition: service_healthy
            images-service:
                condition: service_healthy
            notifications-service:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        env_file: "../.env"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${API_GATEWAY_PORT}/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
        ports:
            - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
        networks:
            - social365-network
