version: "3.8"

services:
    api-gateway:
        container_name: api-gateway
        image: api-gateway
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file:
            - ../../envs/ports.env
        healthcheck:
            test: "curl -f http://localhost:${API_GATEWAY_PORT}/actuator/health || exit 1"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s
        ports:
            - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
