version: "3.8"

services:
    api-gateway:
        container_name: api-gateway
        image: api-gateway
        depends_on:
            eureka-registry:
                condition: service_healthy
            config-server:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file: .env
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${API_GATEWAY_PORT}/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
        ports:
            - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
        networks:
            - social365-network
