version: "3.8"

services:
    config-server:
        container_name: config-server
        image: config-server
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file:
            -   ../../envs/ports.env
        healthcheck:
            test: "curl -f http://localhost:${CONFIG_SERVER_PORT}/actuator/health || exit 1"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s
        ports:
            - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
