services:
    config-server:
        container_name: ${CONFIG_SERVER_HOSTNAME}
        hostname: ${CONFIG_SERVER_HOSTNAME}
        image: ${CONFIG_SERVER_HOSTNAME}
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
            - path: "../.env"
              required: true
        ports:
            - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
        networks:
            - social365-network
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${CONFIG_SERVER_PORT}/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - "./:/home/config-server"
