version: "3.8"

services:
    config-server:
        container_name: config-server
        image: config-server
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file: .env
        ports:
            - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
        networks:
            - social365-network
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:8888/actuator/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
