FROM alpine:3.19.1 AS build

RUN apk update --no-cache && apk add --no-cache gradle

WORKDIR /config-server

COPY build.gradle .

COPY settings.gradle .

COPY src/ src/

RUN gradle build -x test

RUN mv build/libs/config-server-0.0.1-SNAPSHOT.jar config-server.jar

FROM alpine:3.19.1

WORKDIR /config-server

RUN apk update --no-cache && apk add --no-cache openjdk17-jre

COPY --from=build /config-server/config-server.jar .

EXPOSE 8080

CMD ["java", "-jar", "config-server.jar"]
