services:
    profile-neo4j:
        container_name: ${PROFILE_NEO4J_HOSTNAME}
        hostname: ${PROFILE_NEO4J_HOSTNAME}
        image: neo4j:5.18-community-bullseye
        env_file:
            -   path: "../.env"
                required: true
        ports:
            - "7600:7687"
            - "7474:7474"
        networks:
            - profiles-network

    profile-service:
        container_name: ${PROFILE_SERVICE_HOSTNAME}
        image: ${PROFILE_SERVICE_HOSTNAME}
        hostname: ${PROFILE_SERVICE_HOSTNAME}
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file:
            -   path: "../.env"
                required: true
        networks:
            - social365-network
            - profiles-network
        ports:
            - "8083:8083"
        depends_on:
            config-server:
                condition: service_healthy
            eureka-registry:
                condition: service_healthy
            profile-neo4j:
                condition: service_started

networks:
    profiles-network:
        driver: bridge
