FROM alpine:3.19.1

RUN apk update --no-cache && apk upgrade --no-cache && apk add --no-cache gradle openjdk17 curl

WORKDIR /home/profile-service

EXPOSE 8080

EXPOSE 5005

CMD ["gradle", "bootRun"]
