server:
    port: ${API_GATEWAY_PORT}

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-registry:8761/eureka/

        register-with-eureka: false

        fetch-registry: true

    instance:
        hostname: eureka-registry

spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true

            routes:
                -   id: images-service
                    uri: http://images-service:8081
                    predicates:
                        - Path=/api/v1/images/**
