server:
    port: ${API_GATEWAY_PORT}

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URI}

        register-with-eureka: false

        fetch-registry: true

    instance:
        hostname: ${EUREKA_REGISTRY_HOSTNAME}

spring:
    application:
        name: ${API_GATEWAY_HOSTNAME}

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true

            routes:
                -   id: ${IMAGES_SERVICE_HOSTNAME}
                    uri: http://${IMAGES_SERVICE_HOSTNAME}:${IMAGES_SERVICE_PORT}
                    predicates:
                        - Path=/api/v1/images/**

                -   id: ${PROFILE_SERVICE_HOSTNAME}
                    uri: http://${PROFILE_SERVICE_HOSTNAME}:${PROFILE_SERVICE_PORT}
                    predicates:
                        - Path=/api/v1/profile/**

                -   id: ${POSTS_SERVICE_HOSTNAME}
                    uri: http://${POSTS_SERVICE_HOSTNAME}:${POSTS_SERVICE_PORT}
                    predicates:
                        - Path=/api/v1/posts/**

management:
    endpoints:
        web:
            exposure:
                include: "*"
