server:
    port: ${IMAGES_SERVICE_PORT}

    server-header: ""

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

spring:
    datasource:
        url: ${IMAGES_SPRING_DATASOURCE_URL}
        username: ${IMAGES_POSTGRES_USER}
        password: ${IMAGES_POSTGRES_PASSWORD}

    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
            enabled: true

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

                format_sql: true

eureka:
    client:
        instance:
            hostname: ${EUREKA_REGISTRY_HOSTNAME}

        service-url:
            defaultZone: ${EUREKA_SERVER_URI}

        register-with-eureka: true
        fetch-registry: true
