server:
    port: ${IMAGES_SERVICE_PORT}

    cloud:
        config:
            fail-fast: true

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

eureka:
    client:
        instance:
            hostname: ${EUREKA_HOSTNAME}
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_URI}

management:
    endpoints:
        web:
            exposure:
                include: "health"