server:
    port: ${IMAGES_SERVICE_PORT:8081}

    servlet:
        context-path: /

    server-header: ""

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

openapi:
    service:
        title: Images Service
        version: 1.0.0
        url: http://${API_GATEWAY_HOSTNAME}:${API_GATEWAY_PORT}

springdoc:
    api-docs:
        path: /${IMAGES_SERVICE_HOSTNAME}/v3/api-docs
    swagger-ui:
        path: /${IMAGES_SERVICE_HOSTNAME}/swagger-ui.html

spring:
    datasource:
        url: ${IMAGES_SPRING_DATASOURCE_URL}
        username: ${IMAGES_POSTGRES_USER}
        password: ${IMAGES_POSTGRES_PASSWORD}

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}
                    jwk-set-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}/oauth2/jwks
                    jws-algorithms: ${JWS_ALGORITHM}

    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
            enabled: true

    kafka:
        consumer:
            auto-offset-reset: earliest
            key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            bootstrap-servers: ${KAFKA_BROKER_HOSTNAME}:${KAFKA_PORT}
            properties:
                spring.json.trusted.packages: '*'
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
            group-id: ${KAFKA_NOTIFICATIONS_GROUP_ID}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

                format_sql: true

kafka:
    topics:
        account-created: ${KAFKA_ACCOUNT_CREATED_TOPIC}
        post-deleted: ${KAFKA_POST_DELETED_TOPIC}

    group-ids:
        notifications: ${KAFKA_NOTIFICATIONS_GROUP_ID}

eureka:
    client:
        instance:
            hostname: ${EUREKA_REGISTRY_HOSTNAME}

        service-url:
            defaultZone: ${EUREKA_SERVER_URI}

        register-with-eureka: true
        fetch-registry: true
