server:
    port: ${POSTS_SERVICE_PORT}

    servlet:
        context-path: /

    server-header: ""

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

openapi:
    service:
        title: ${POSTS_SERVICE_HOSTNAME}
        version: 1.0.0
        url: http://${API_GATEWAY_HOSTNAME}:${API_GATEWAY_PORT}

springdoc:
    api-docs:
        path: /${POSTS_SERVICE_HOSTNAME}/v3/api-docs
    swagger-ui:
        path: /${POSTS_SERVICE_HOSTNAME}/swagger-ui.html

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}
                    jwk-set-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}/oauth2/jwks
                    jws-algorithms: ${JWS_ALGORITHM}

    cassandra:
        schema-action: create_if_not_exists

        request:
            timeout: 10s

        connection:
            connect-timeout: 10s
            init-query-timeout: 10s

        username: ${POSTS_CASSANDRA_USERNAME}
        password: ${POSTS_CASSANDRA_PASSWORD}
        port: ${POSTS_CASSANDRA_PORT}
        keyspace-name: ${POSTS_CASSANDRA_KEYSPACE_NAME}
        contact-points: ${POSTS_CASSANDRA_HOSTNAME}
        local-datacenter: ${POSTS_CASSANDRA_DATACENTER}

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URI}

        register-with-eureka: true
        fetch-registry: true

    instance:
        hostname: ${EUREKA_REGISTRY_HOSTNAME}
