server:
    port: ${PROFILE_SERVICE_PORT}

    server-header: ""

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512

logging:
    level:
        org.springframework.data.neo4j.cypher: ERROR

spring:
    neo4j:
        uri: ${NEO4J_URI}
        authentication:
            username: ${NEO4J_USERNAME}
            password: ${NEO4J_PASSWORD}

    cloud:
        refresh:
            enabled: false

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}
                    jwk-set-uri: http://${AUTH_SERVICE_HOSTNAME}:${AUTH_SERVICE_PORT}/oauth2/jwks
                    jws-algorithms: ${JWS_ALGORITHM}

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URI}

        register-with-eureka: true
        fetch-registry: true

    instance:
        hostname: ${EUREKA_REGISTRY_HOSTNAME}
