services:
    social365-keycloak-initializer:
        container_name: social365-keycloak-initializer
        image: social365-keycloak-initializer
        build:
            context: keycloak-initializer
            dockerfile: Dockerfile.prod
        depends_on:
            social365-keycloak:
                condition: service_healthy
        env_file: .env
        environment:
            - KCCFG_OVERRIDE_EXISTING=false
        networks:
            - social365-network

    social365-keycloak:
        container_name: social365-keycloak
        image: quay.io/keycloak/keycloak:20.0.1
        depends_on:
            social365-keycloak-postgres:
                condition: service_healthy
        env_file: .env
        command: start-dev
        ports:
            - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"
        healthcheck:
            test: "curl -f http://localhost:${KEYCLOAK_PORT}/admin || exit 1"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s
        networks:
            - social365-network

    social365-keycloak-postgres:
        container_name: social365-keycloak-postgres
        image: postgres:alpine
        env_file: .env
        ports:
            - "${KEYCLOAK_POSTGRES_PORT}:${POSTGRES_PORT}"
        healthcheck:
            test: "pg_isready -U keycloak"
            interval: 1s
            retries: 30
            start_period: 15s
            timeout: 5s
        networks:
            - social365-network
