services:
    images-postgres:
        env_file:
            - .env
        image: postgres:alpine
        environment:
            POSTGRES_DB: ${IMAGES_POSTGRES_DB}
            POSTGRES_USER: ${IMAGES_POSTGRES_USER}
            POSTGRES_PASSWORD: ${IMAGES_POSTGRES_PASSWORD}
        ports:
            - "5000:5432"
        networks:
            - social365-network
