server:
    port: ${CONFIG_SERVER_PORT}

    http2:
        enabled: true

    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 512


spring:
    profiles:
        active: native
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configs
management:
    endpoints:
        web:
            exposure:
                include: health
