services:
    frontend-client:
        container_name: ${FRONTEND_HOSTNAME}
        image: ${FRONTEND_HOSTNAME}:prod
        hostname: ${FRONTEND_HOSTNAME}
        build:
            context: .
            dockerfile: Dockerfile
        env_file: "../.env"
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${FRONTEND_PORT}" ]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - social365-network
