services:
    frontend-client:
        container_name: ${FRONTEND_HOSTNAME}
        image: ${FRONTEND_HOSTNAME}:dev
        hostname: ${FRONTEND_HOSTNAME}
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: "../.env"
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${FRONTEND_PORT}" ]
            interval: 15s
            timeout: 5s
            retries: 5
        volumes:
            - "./:/home/frontend-client"
        networks:
            - social365-network
