version: "3.8"

services:
    frontend-client:
        container_name: frontend-client
        image: frontend-client
        depends_on:
            - api-gateway
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file: .env
        ports:
            - "${FRONTEND_PORT}:${NGINX_PORT}"
        healthcheck:
            test: "curl -f http://localhost:${FRONTEND_PORT} || exit 1"
        networks:
            - social365-network
