services:
    frontend-client:
        container_name: frontend-client
        image: frontend-client
        build:
            context: .
            dockerfile: Dockerfile.prod
        env_file: ../.env
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_NGINX_PORT}"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:${FRONTEND_NGINX_PORT}" ]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - social365-network
