spring:
    application:
        name: ${NOTIFICATIONS_GATEWAY_HOSTNAME}

    config:
        import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME}:${CONFIG_SERVER_PORT}

logging:
    level:
        org:
            springframework:
                web:
                    socket: TRACE


