export enum AboutContactMappings {

    ABOUT_CONTACT_API_MAPPING = "/api/v1/profile/about/contact",

    UPDATE_PROFILE_PHONE_NUMBER_MAPPING = ABOUT_CONTACT_API_MAPPING + "/updatePhone",

    UPDATE_PROFILE_EMAIL_PRIVACY_LEVEL_MAPPING = ABOUT_CONTACT_API_MAPPING + "/updateEmailPrivacyLevel",

    DELETE_PROFILE_PHONE_NUMBER_MAPPING = ABOUT_CONTACT_API_MAPPING + "/deletePhone",

}
