export enum AboutExperienceMappings {
    PROFILE_EXPERIENCE_API_MAPPING = "/api/v1/profile/about/experience",

    UPDATE_PROFILE_WORK_PLACE_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateWorkPlace",

    UPDATE_PROFILE_EDUCATION_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateEducation",

    DELETE_PROFILE_WORK_PLACE_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteWorkPlace",

    DELETE_PROFILE_EDUCATION_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteEducation",

    UPDATE_PROFILE_HIGH_SCHOOL_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateHighSchool",

    DELETE_PROFILE_HIGH_SCHOOL_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteHighSchool",
}
