export enum AboutExperienceMappings {
    PROFILE_EXPERIENCE_API_MAPPING = "/api/v1/profile/about/experience",

    UPDATE_PROFILE_CURRENT_CITY_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateCurrentCity",

    UPDATE_PROFILE_HOME_TOWN_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateHomeTown",

    UPDATE_PROFILE_WORK_PLACE_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateWorkPlace",

    UPDATE_PROFILE_EDUCATION_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateEducation",

    UPDATE_PROFILE_RELATIONSHIP_STATUS_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateRelationshipStatus",
    
    DELETE_PROFILE_CURRENT_CITY_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteCurrentCity",

    DELETE_PROFILE_HOME_TOWN_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteHomeTown",

    DELETE_PROFILE_WORK_PLACE_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteWorkPlace",

    DELETE_PROFILE_EDUCATION_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteEducation",

    DELETE_PROFILE_RELATIONSHIP_STATUS_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteRelationshipStatus",

    UPDATE_PROFILE_HIGH_SCHOOL_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/updateHighSchool",

    DELETE_PROFILE_HIGH_SCHOOL_MAPPING = PROFILE_EXPERIENCE_API_MAPPING + "/deleteHighSchool",
}
