export enum AboutDetailsMappings {
    ABOUT_DETAILS_MAPPING = "/api/v1/profile/about/details",

    UPDATE_PROFILE_GENDER_MAPPING = ABOUT_DETAILS_MAPPING + "/updateDetails",

    DELETE_PROFILE_GENDER_MAPPING = ABOUT_DETAILS_MAPPING + "/deleteDetails",

    UPDATE_PROFILE_DATE_OF_BIRTH_MAPPING = ABOUT_DETAILS_MAPPING + "/updateDateOfBirth",

    UPDATE_PROFILE_RELATIONSHIP_STATUS_MAPPING = ABOUT_DETAILS_MAPPING + "/updateRelationshipStatus",

    DELETE_PROFILE_CURRENT_CITY_MAPPING = ABOUT_DETAILS_MAPPING + "/deleteCurrentCity",

    DELETE_PROFILE_HOME_TOWN_MAPPING = ABOUT_DETAILS_MAPPING + "/deleteHomeTown",

    DELETE_PROFILE_RELATIONSHIP_STATUS_MAPPING = ABOUT_DETAILS_MAPPING + "/deleteRelationshipStatus",

    UPDATE_PROFILE_CURRENT_CITY_MAPPING = ABOUT_DETAILS_MAPPING + "/updateCurrentCity",

    UPDATE_PROFILE_HOME_TOWN_MAPPING = ABOUT_DETAILS_MAPPING + "/updateHomeTown",
}
