name: Test Api Gateway with Gradle

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "main",  "devel" ]

permissions:
    contents: read

jobs:
    test-app-with-gradle:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    gradle-version: '8.2'
                    arguments: build
                    build-root-directory: services/api-gateway
