name: Test Services With Gradle

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "main",  "devel" ]

permissions:
    contents: read

jobs:
    test-api-gateway-with-gradle:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                env:
                    API_GATEWAY_PORT: 8222
                with:
                    gradle-version: '8.2'
                    arguments: build
                    build-root-directory: services/api-gateway

    test-config-server-with-gradle:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                env:
                    CONFIG_SERVER_PORT: 8888
                    CONFIG_SERVER_HOSTNAME: localhost
                with:
                    gradle-version: '8.2'
                    arguments: build
                    build-root-directory: services/config-server

    test-discovery-server-with-gradle:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                env:
                    EUREKA_REGISTRY_HOSTNAME: localhost
                    EUREKA_REGISTRY_PORT: 8761
                    EUREKA_SERVER_URI: http://localhost:8761/eureka
                with:
                    gradle-version: '8.2'
                    arguments: build
                    build-root-directory: services/eureka-registry

    test-images-service-with-gradle:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                env:
                    IMAGES_SERVICE_HOSTNAME: images-service
                    IMAGES_POSTGRES_HOSTNAME: images-postgres
                    IMAGES_POSTGRES_PORT: 5000
                    IMAGES_POSTGRES_DB: images
                    IMAGES_POSTGRES_USER: postgres
                    IMAGES_POSTGRES_PASSWORD: images
                    IMAGE_VOLUME_PATH: /usr/share/images
                    IMAGES_SERVICE_PORT: 8081
                    IMAGES_SPRING_DATASOURCE_URL: jdbc:postgresql://images-postgres:5432/images
                    CONFIG_SERVER_PORT: 8888
                    CONFIG_SERVER_HOSTNAME: localhost
                with:
                    gradle-version: '8.2'
                    arguments: build
                    build-root-directory: services/images/images-service
